name: Build & Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
        name: 'Checkout repo'
      - uses: lukka/get-cmake@latest
        name: 'Setup CMake'
      - name: Build binaries
        run: |
          cmake -B build
          cmake --build build --config Release
          mkdir stoat-kbhook-${{github.ref_name}}
          cp build/Release/kbhook_app.exe stoat-kbhook-${{github.ref_name}}/kbhook_app.exe
          cp build/Release/kbhook_hook.dll stoat-kbhook-${{github.ref_name}}/kbhook_hook.dll
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "stoat-kbhook-${{github.ref_name}}/*"